// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: budget_summary.sql

package db

import (
	"context"
)

const sumActualSpendByMonth = `-- name: SumActualSpendByMonth :one
SELECT COALESCE(SUM(je.amount), 0)::INTEGER AS total
FROM journal_entries je
WHERE je.user_id = $1
  AND TO_CHAR(je.transaction_date, 'YYYY-MM') = $2::text
  AND je.is_excluded = false
`

type SumActualSpendByMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) SumActualSpendByMonth(ctx context.Context, arg SumActualSpendByMonthParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumActualSpendByMonth, arg.UserID, arg.Column2)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const sumRecurringFixed = `-- name: SumRecurringFixed :one
SELECT COALESCE(SUM(amount), 0)::INTEGER AS total
FROM recurring_expenses
WHERE user_id = $1 AND type = 'fixed' AND amount IS NOT NULL
`

func (q *Queries) SumRecurringFixed(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, sumRecurringFixed, userID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const sumSavingsMonthly = `-- name: SumSavingsMonthly :one
SELECT COALESCE(SUM(monthly_amount), 0)::INTEGER AS total
FROM savings_goals
WHERE user_id = $1
`

func (q *Queries) SumSavingsMonthly(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, sumSavingsMonthly, userID)
	var total int32
	err := row.Scan(&total)
	return total, err
}
