// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: budgets.sql

package db

import (
	"context"
)

const getBudgetByUser = `-- name: GetBudgetByUser :one
SELECT monthly_budget, goal_text, goal_amount
FROM budgets
WHERE user_id = $1
`

type GetBudgetByUserRow struct {
	MonthlyBudget int32   `json:"monthly_budget"`
	GoalText      *string `json:"goal_text"`
	GoalAmount    int32   `json:"goal_amount"`
}

func (q *Queries) GetBudgetByUser(ctx context.Context, userID int32) (GetBudgetByUserRow, error) {
	row := q.db.QueryRow(ctx, getBudgetByUser, userID)
	var i GetBudgetByUserRow
	err := row.Scan(&i.MonthlyBudget, &i.GoalText, &i.GoalAmount)
	return i, err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (user_id, monthly_budget, goal_text, goal_amount)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
  SET monthly_budget = EXCLUDED.monthly_budget,
      goal_text      = EXCLUDED.goal_text,
      goal_amount    = EXCLUDED.goal_amount,
      updated_at     = NOW()
RETURNING monthly_budget, goal_text, goal_amount
`

type UpsertBudgetParams struct {
	UserID        int32   `json:"user_id"`
	MonthlyBudget int32   `json:"monthly_budget"`
	GoalText      *string `json:"goal_text"`
	GoalAmount    int32   `json:"goal_amount"`
}

type UpsertBudgetRow struct {
	MonthlyBudget int32   `json:"monthly_budget"`
	GoalText      *string `json:"goal_text"`
	GoalAmount    int32   `json:"goal_amount"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (UpsertBudgetRow, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.UserID,
		arg.MonthlyBudget,
		arg.GoalText,
		arg.GoalAmount,
	)
	var i UpsertBudgetRow
	err := row.Scan(&i.MonthlyBudget, &i.GoalText, &i.GoalAmount)
	return i, err
}
