// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_groups.sql

package db

import (
	"context"
)

const countActiveExpenseCategoriesByGroup = `-- name: CountActiveExpenseCategoriesByGroup :one
SELECT COUNT(*) FROM expense_categories
WHERE group_id = $1 AND user_id = $2 AND is_deleted = false
`

type CountActiveExpenseCategoriesByGroupParams struct {
	GroupID int32 `json:"group_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) CountActiveExpenseCategoriesByGroup(ctx context.Context, arg CountActiveExpenseCategoriesByGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveExpenseCategoriesByGroup, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategoryGroup = `-- name: CreateCategoryGroup :one
INSERT INTO category_groups (user_id, group_name, statement_type_id, description)
VALUES ($1, $2, $3, $4)
RETURNING id, group_name, statement_type_id, description
`

type CreateCategoryGroupParams struct {
	UserID          int32   `json:"user_id"`
	GroupName       string  `json:"group_name"`
	StatementTypeID int32   `json:"statement_type_id"`
	Description     *string `json:"description"`
}

type CreateCategoryGroupRow struct {
	ID              int32   `json:"id"`
	GroupName       string  `json:"group_name"`
	StatementTypeID int32   `json:"statement_type_id"`
	Description     *string `json:"description"`
}

func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (CreateCategoryGroupRow, error) {
	row := q.db.QueryRow(ctx, createCategoryGroup,
		arg.UserID,
		arg.GroupName,
		arg.StatementTypeID,
		arg.Description,
	)
	var i CreateCategoryGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.StatementTypeID,
		&i.Description,
	)
	return i, err
}

const getCategoryGroupByID = `-- name: GetCategoryGroupByID :one
SELECT
  cg.id,
  cg.group_name,
  cg.description,
  cg.statement_type_id,
  st.type_code AS statement_type_code,
  st.statement_type_name,
  st.display_order AS statement_type_display_order
FROM category_groups cg
JOIN statement_types st ON cg.statement_type_id = st.id
WHERE cg.id = $1 AND cg.user_id = $2 AND cg.is_deleted = false
`

type GetCategoryGroupByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetCategoryGroupByIDRow struct {
	ID                        int32   `json:"id"`
	GroupName                 string  `json:"group_name"`
	Description               *string `json:"description"`
	StatementTypeID           int32   `json:"statement_type_id"`
	StatementTypeCode         string  `json:"statement_type_code"`
	StatementTypeName         string  `json:"statement_type_name"`
	StatementTypeDisplayOrder int32   `json:"statement_type_display_order"`
}

func (q *Queries) GetCategoryGroupByID(ctx context.Context, arg GetCategoryGroupByIDParams) (GetCategoryGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryGroupByID, arg.ID, arg.UserID)
	var i GetCategoryGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Description,
		&i.StatementTypeID,
		&i.StatementTypeCode,
		&i.StatementTypeName,
		&i.StatementTypeDisplayOrder,
	)
	return i, err
}

const listCategoryGroupsByUser = `-- name: ListCategoryGroupsByUser :many
SELECT
  cg.id,
  cg.group_name,
  cg.description,
  cg.statement_type_id,
  st.type_code AS statement_type_code,
  st.statement_type_name,
  st.display_order AS statement_type_display_order
FROM category_groups cg
JOIN statement_types st ON cg.statement_type_id = st.id
WHERE cg.user_id = $1 AND cg.is_deleted = false
ORDER BY cg.group_name ASC
`

type ListCategoryGroupsByUserRow struct {
	ID                        int32   `json:"id"`
	GroupName                 string  `json:"group_name"`
	Description               *string `json:"description"`
	StatementTypeID           int32   `json:"statement_type_id"`
	StatementTypeCode         string  `json:"statement_type_code"`
	StatementTypeName         string  `json:"statement_type_name"`
	StatementTypeDisplayOrder int32   `json:"statement_type_display_order"`
}

func (q *Queries) ListCategoryGroupsByUser(ctx context.Context, userID int32) ([]ListCategoryGroupsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoryGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryGroupsByUserRow
	for rows.Next() {
		var i ListCategoryGroupsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Description,
			&i.StatementTypeID,
			&i.StatementTypeCode,
			&i.StatementTypeName,
			&i.StatementTypeDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategoryGroup = `-- name: SoftDeleteCategoryGroup :execrows
UPDATE category_groups
SET is_deleted = true, deleted_at = NOW(), updated_at = NOW(), version = version + 1
WHERE id = $1 AND user_id = $2 AND is_deleted = false
`

type SoftDeleteCategoryGroupParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) SoftDeleteCategoryGroup(ctx context.Context, arg SoftDeleteCategoryGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCategoryGroup, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCategoryGroupByID = `-- name: UpdateCategoryGroupByID :execrows
UPDATE category_groups
SET group_name = $3, statement_type_id = $4, description = $5, updated_at = NOW(), version = version + 1
WHERE id = $1 AND user_id = $2 AND is_deleted = false
`

type UpdateCategoryGroupByIDParams struct {
	ID              int32   `json:"id"`
	UserID          int32   `json:"user_id"`
	GroupName       string  `json:"group_name"`
	StatementTypeID int32   `json:"statement_type_id"`
	Description     *string `json:"description"`
}

func (q *Queries) UpdateCategoryGroupByID(ctx context.Context, arg UpdateCategoryGroupByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategoryGroupByID,
		arg.ID,
		arg.UserID,
		arg.GroupName,
		arg.StatementTypeID,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
