// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_groups.sql

package db

import (
	"context"
)

const listCategoryGroupsByUser = `-- name: ListCategoryGroupsByUser :many
SELECT
  cg.id,
  cg.group_name,
  cg.description,
  cg.statement_type_id,
  st.type_code AS statement_type_code,
  st.statement_type_name,
  st.display_order AS statement_type_display_order
FROM category_groups cg
JOIN statement_types st ON cg.statement_type_id = st.id
WHERE cg.user_id = $1 AND cg.is_deleted = false
ORDER BY cg.group_name ASC
`

type ListCategoryGroupsByUserRow struct {
	ID                        int32   `json:"id"`
	GroupName                 string  `json:"group_name"`
	Description               *string `json:"description"`
	StatementTypeID           int32   `json:"statement_type_id"`
	StatementTypeCode         string  `json:"statement_type_code"`
	StatementTypeName         string  `json:"statement_type_name"`
	StatementTypeDisplayOrder int32   `json:"statement_type_display_order"`
}

func (q *Queries) ListCategoryGroupsByUser(ctx context.Context, userID int32) ([]ListCategoryGroupsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoryGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryGroupsByUserRow
	for rows.Next() {
		var i ListCategoryGroupsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Description,
			&i.StatementTypeID,
			&i.StatementTypeCode,
			&i.StatementTypeName,
			&i.StatementTypeDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
