// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: daily_notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailyNote = `-- name: DeleteDailyNote :exec
DELETE FROM daily_notes
WHERE user_id = $1 AND date = $2
`

type DeleteDailyNoteParams struct {
	UserID int32       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) DeleteDailyNote(ctx context.Context, arg DeleteDailyNoteParams) error {
	_, err := q.db.Exec(ctx, deleteDailyNote, arg.UserID, arg.Date)
	return err
}

const getDailyNotesByMonth = `-- name: GetDailyNotesByMonth :many
SELECT date, note FROM daily_notes
WHERE user_id = $1
  AND date >= $2::date
  AND date < ($2::date + INTERVAL '1 month')
ORDER BY date DESC
`

type GetDailyNotesByMonthParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type GetDailyNotesByMonthRow struct {
	Date pgtype.Date `json:"date"`
	Note string      `json:"note"`
}

func (q *Queries) GetDailyNotesByMonth(ctx context.Context, arg GetDailyNotesByMonthParams) ([]GetDailyNotesByMonthRow, error) {
	rows, err := q.db.Query(ctx, getDailyNotesByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyNotesByMonthRow
	for rows.Next() {
		var i GetDailyNotesByMonthRow
		if err := rows.Scan(&i.Date, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyNote = `-- name: UpsertDailyNote :one
INSERT INTO daily_notes (user_id, date, note)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, date) DO UPDATE
  SET note       = EXCLUDED.note,
      updated_at = NOW()
RETURNING date, note
`

type UpsertDailyNoteParams struct {
	UserID int32       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Note   string      `json:"note"`
}

type UpsertDailyNoteRow struct {
	Date pgtype.Date `json:"date"`
	Note string      `json:"note"`
}

func (q *Queries) UpsertDailyNote(ctx context.Context, arg UpsertDailyNoteParams) (UpsertDailyNoteRow, error) {
	row := q.db.QueryRow(ctx, upsertDailyNote, arg.UserID, arg.Date, arg.Note)
	var i UpsertDailyNoteRow
	err := row.Scan(&i.Date, &i.Note)
	return i, err
}
