// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDailyExpenseSumsForMonth = `-- name: ListDailyExpenseSumsForMonth :many
SELECT
  je.transaction_date::text AS date,
  st.type_code,
  CAST(SUM(je.amount) AS integer) AS daily_sum
FROM journal_entries je
JOIN expense_categories ec ON je.category_id = ec.id
JOIN category_groups    cg ON ec.group_id     = cg.id
JOIN statement_types    st ON cg.statement_type_id = st.id
WHERE je.user_id      = $1
  AND je.is_excluded  = false
  AND st.type_code    IN ('food', 'other')
  AND je.transaction_date >= $2::date
  AND je.transaction_date <  $2::date + INTERVAL '1 month'
GROUP BY je.transaction_date, st.type_code
ORDER BY je.transaction_date ASC
`

type ListDailyExpenseSumsForMonthParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListDailyExpenseSumsForMonthRow struct {
	Date     string `json:"date"`
	TypeCode string `json:"type_code"`
	DailySum int32  `json:"daily_sum"`
}

// Returns per-day, per-type_code subtotals for the target month.
// Only includes is_excluded=false entries with type_code 'food' or 'other'.
func (q *Queries) ListDailyExpenseSumsForMonth(ctx context.Context, arg ListDailyExpenseSumsForMonthParams) ([]ListDailyExpenseSumsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listDailyExpenseSumsForMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyExpenseSumsForMonthRow
	for rows.Next() {
		var i ListDailyExpenseSumsForMonthRow
		if err := rows.Scan(&i.Date, &i.TypeCode, &i.DailySum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
