// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_categories.sql

package db

import (
	"context"
)

const getActiveExpenseCategoryByID = `-- name: GetActiveExpenseCategoryByID :one
SELECT id, user_id, group_id, is_deleted
FROM expense_categories
WHERE id = $1 AND user_id = $2 AND is_deleted = false
`

type GetActiveExpenseCategoryByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetActiveExpenseCategoryByIDRow struct {
	ID        int32 `json:"id"`
	UserID    int32 `json:"user_id"`
	GroupID   int32 `json:"group_id"`
	IsDeleted bool  `json:"is_deleted"`
}

// Used to validate category_id when creating/updating a journal entry
func (q *Queries) GetActiveExpenseCategoryByID(ctx context.Context, arg GetActiveExpenseCategoryByIDParams) (GetActiveExpenseCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveExpenseCategoryByID, arg.ID, arg.UserID)
	var i GetActiveExpenseCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.IsDeleted,
	)
	return i, err
}

const listExpenseCategoriesByUser = `-- name: ListExpenseCategoriesByUser :many
SELECT
  ec.id,
  ec.category_name,
  ec.description,
  ec.group_id,
  cg.group_name
FROM expense_categories ec
JOIN category_groups cg ON ec.group_id = cg.id
WHERE ec.user_id = $1
  AND ec.is_deleted = false
  AND cg.is_deleted = false
ORDER BY cg.group_name ASC, ec.category_name ASC
`

type ListExpenseCategoriesByUserRow struct {
	ID           int32   `json:"id"`
	CategoryName string  `json:"category_name"`
	Description  *string `json:"description"`
	GroupID      int32   `json:"group_id"`
	GroupName    string  `json:"group_name"`
}

func (q *Queries) ListExpenseCategoriesByUser(ctx context.Context, userID int32) ([]ListExpenseCategoriesByUserRow, error) {
	rows, err := q.db.Query(ctx, listExpenseCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseCategoriesByUserRow
	for rows.Next() {
		var i ListExpenseCategoriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.Description,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
