// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: income_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncomeRecord = `-- name: CreateIncomeRecord :one
INSERT INTO income_records (user_id, transaction_date, amount, name, income_type, emoji, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, transaction_date, amount, name, income_type, emoji, note
`

type CreateIncomeRecordParams struct {
	UserID          int32       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Amount          int32       `json:"amount"`
	Name            string      `json:"name"`
	IncomeType      string      `json:"income_type"`
	Emoji           string      `json:"emoji"`
	Note            string      `json:"note"`
}

type CreateIncomeRecordRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Amount          int32       `json:"amount"`
	Name            string      `json:"name"`
	IncomeType      string      `json:"income_type"`
	Emoji           string      `json:"emoji"`
	Note            string      `json:"note"`
}

func (q *Queries) CreateIncomeRecord(ctx context.Context, arg CreateIncomeRecordParams) (CreateIncomeRecordRow, error) {
	row := q.db.QueryRow(ctx, createIncomeRecord,
		arg.UserID,
		arg.TransactionDate,
		arg.Amount,
		arg.Name,
		arg.IncomeType,
		arg.Emoji,
		arg.Note,
	)
	var i CreateIncomeRecordRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Amount,
		&i.Name,
		&i.IncomeType,
		&i.Emoji,
		&i.Note,
	)
	return i, err
}

const deleteIncomeRecord = `-- name: DeleteIncomeRecord :exec
DELETE FROM income_records WHERE id = $1 AND user_id = $2
`

type DeleteIncomeRecordParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteIncomeRecord(ctx context.Context, arg DeleteIncomeRecordParams) error {
	_, err := q.db.Exec(ctx, deleteIncomeRecord, arg.ID, arg.UserID)
	return err
}

const getBaseIncome = `-- name: GetBaseIncome :one
SELECT amount FROM base_income_settings WHERE user_id = $1
`

func (q *Queries) GetBaseIncome(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getBaseIncome, userID)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}

const listIncomeRecords = `-- name: ListIncomeRecords :many
SELECT id, transaction_date, amount, name, income_type, emoji, note
FROM income_records
WHERE user_id = $1 AND TO_CHAR(transaction_date, 'YYYY-MM') = $2::text
ORDER BY transaction_date DESC, id DESC
`

type ListIncomeRecordsParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

type ListIncomeRecordsRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Amount          int32       `json:"amount"`
	Name            string      `json:"name"`
	IncomeType      string      `json:"income_type"`
	Emoji           string      `json:"emoji"`
	Note            string      `json:"note"`
}

func (q *Queries) ListIncomeRecords(ctx context.Context, arg ListIncomeRecordsParams) ([]ListIncomeRecordsRow, error) {
	rows, err := q.db.Query(ctx, listIncomeRecords, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomeRecordsRow
	for rows.Next() {
		var i ListIncomeRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Amount,
			&i.Name,
			&i.IncomeType,
			&i.Emoji,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeByMonth = `-- name: SumIncomeByMonth :one
SELECT COALESCE(SUM(amount), 0)::INTEGER AS total
FROM income_records
WHERE user_id = $1 AND TO_CHAR(transaction_date, 'YYYY-MM') = $2::text
`

type SumIncomeByMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) SumIncomeByMonth(ctx context.Context, arg SumIncomeByMonthParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumIncomeByMonth, arg.UserID, arg.Column2)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const updateIncomeRecord = `-- name: UpdateIncomeRecord :one
UPDATE income_records
SET transaction_date = $3, amount = $4, name = $5, income_type = $6, emoji = $7, note = $8, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, transaction_date, amount, name, income_type, emoji, note
`

type UpdateIncomeRecordParams struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Amount          int32       `json:"amount"`
	Name            string      `json:"name"`
	IncomeType      string      `json:"income_type"`
	Emoji           string      `json:"emoji"`
	Note            string      `json:"note"`
}

type UpdateIncomeRecordRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Amount          int32       `json:"amount"`
	Name            string      `json:"name"`
	IncomeType      string      `json:"income_type"`
	Emoji           string      `json:"emoji"`
	Note            string      `json:"note"`
}

func (q *Queries) UpdateIncomeRecord(ctx context.Context, arg UpdateIncomeRecordParams) (UpdateIncomeRecordRow, error) {
	row := q.db.QueryRow(ctx, updateIncomeRecord,
		arg.ID,
		arg.UserID,
		arg.TransactionDate,
		arg.Amount,
		arg.Name,
		arg.IncomeType,
		arg.Emoji,
		arg.Note,
	)
	var i UpdateIncomeRecordRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Amount,
		&i.Name,
		&i.IncomeType,
		&i.Emoji,
		&i.Note,
	)
	return i, err
}

const upsertBaseIncome = `-- name: UpsertBaseIncome :one
INSERT INTO base_income_settings (user_id, amount)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET amount = EXCLUDED.amount, updated_at = NOW()
RETURNING amount
`

type UpsertBaseIncomeParams struct {
	UserID int32 `json:"user_id"`
	Amount int32 `json:"amount"`
}

func (q *Queries) UpsertBaseIncome(ctx context.Context, arg UpsertBaseIncomeParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertBaseIncome, arg.UserID, arg.Amount)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}
