// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: journal_entries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  transaction_date, item, amount, category_id, user_id, is_excluded, note,
  recurring_expense_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, transaction_date, item, amount, category_id, user_id,
          is_excluded, note, created_at, updated_at, recurring_expense_id
`

type CreateJournalEntryParams struct {
	TransactionDate    pgtype.Date `json:"transaction_date"`
	Item               *string     `json:"item"`
	Amount             int32       `json:"amount"`
	CategoryID         int32       `json:"category_id"`
	UserID             int32       `json:"user_id"`
	IsExcluded         bool        `json:"is_excluded"`
	Note               *string     `json:"note"`
	RecurringExpenseID *int32      `json:"recurring_expense_id"`
}

type CreateJournalEntryRow struct {
	ID                 int32       `json:"id"`
	TransactionDate    pgtype.Date `json:"transaction_date"`
	Item               *string     `json:"item"`
	Amount             int32       `json:"amount"`
	CategoryID         int32       `json:"category_id"`
	UserID             int32       `json:"user_id"`
	IsExcluded         bool        `json:"is_excluded"`
	Note               *string     `json:"note"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	RecurringExpenseID *int32      `json:"recurring_expense_id"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (CreateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TransactionDate,
		arg.Item,
		arg.Amount,
		arg.CategoryID,
		arg.UserID,
		arg.IsExcluded,
		arg.Note,
		arg.RecurringExpenseID,
	)
	var i CreateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Item,
		&i.Amount,
		&i.CategoryID,
		&i.UserID,
		&i.IsExcluded,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecurringExpenseID,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal_entries
WHERE id = $1 AND user_id = $2
`

type DeleteJournalEntryParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteJournalEntry(ctx context.Context, arg DeleteJournalEntryParams) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, arg.ID, arg.UserID)
	return err
}

const listJournalEntriesByMonth = `-- name: ListJournalEntriesByMonth :many
SELECT
  je.id,
  je.transaction_date,
  je.item,
  je.amount,
  je.category_id,
  ec.category_name,
  ec.group_id,
  cg.group_name,
  je.is_excluded,
  je.note,
  je.created_at,
  je.recurring_expense_id
FROM journal_entries je
JOIN expense_categories ec ON je.category_id = ec.id
JOIN category_groups cg ON ec.group_id = cg.id
WHERE je.user_id = $1
  AND je.transaction_date >= $2::date
  AND je.transaction_date < ($2::date + INTERVAL '1 month')
ORDER BY je.transaction_date DESC, je.id DESC
`

type ListJournalEntriesByMonthParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListJournalEntriesByMonthRow struct {
	ID                 int32       `json:"id"`
	TransactionDate    pgtype.Date `json:"transaction_date"`
	Item               *string     `json:"item"`
	Amount             int32       `json:"amount"`
	CategoryID         int32       `json:"category_id"`
	CategoryName       string      `json:"category_name"`
	GroupID            int32       `json:"group_id"`
	GroupName          string      `json:"group_name"`
	IsExcluded         bool        `json:"is_excluded"`
	Note               *string     `json:"note"`
	CreatedAt          time.Time   `json:"created_at"`
	RecurringExpenseID *int32      `json:"recurring_expense_id"`
}

// Joins category and group info for the response.
// Includes soft-deleted categories so historical entries display correctly.
func (q *Queries) ListJournalEntriesByMonth(ctx context.Context, arg ListJournalEntriesByMonthParams) ([]ListJournalEntriesByMonthRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalEntriesByMonthRow
	for rows.Next() {
		var i ListJournalEntriesByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Item,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryName,
			&i.GroupID,
			&i.GroupName,
			&i.IsExcluded,
			&i.Note,
			&i.CreatedAt,
			&i.RecurringExpenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET transaction_date = $3,
    item             = $4,
    amount           = $5,
    category_id      = $6,
    is_excluded      = $7,
    note             = $8,
    updated_at       = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, transaction_date, item, amount, category_id, user_id,
          is_excluded, note, created_at, updated_at
`

type UpdateJournalEntryParams struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	CategoryID      int32       `json:"category_id"`
	IsExcluded      bool        `json:"is_excluded"`
	Note            *string     `json:"note"`
}

type UpdateJournalEntryRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	CategoryID      int32       `json:"category_id"`
	UserID          int32       `json:"user_id"`
	IsExcluded      bool        `json:"is_excluded"`
	Note            *string     `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (UpdateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry,
		arg.ID,
		arg.UserID,
		arg.TransactionDate,
		arg.Item,
		arg.Amount,
		arg.CategoryID,
		arg.IsExcluded,
		arg.Note,
	)
	var i UpdateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Item,
		&i.Amount,
		&i.CategoryID,
		&i.UserID,
		&i.IsExcluded,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
