// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  transaction_date, item, amount, category_id, user_id, is_excluded, note
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, transaction_date, item, amount, category_id, user_id,
          is_excluded, note, created_at, updated_at
`

type CreateJournalEntryParams struct {
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	CategoryID      int32       `json:"category_id"`
	UserID          int32       `json:"user_id"`
	IsExcluded      bool        `json:"is_excluded"`
	Note            *string     `json:"note"`
}

type CreateJournalEntryRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	CategoryID      int32       `json:"category_id"`
	UserID          int32       `json:"user_id"`
	IsExcluded      bool        `json:"is_excluded"`
	Note            *string     `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (CreateJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TransactionDate,
		arg.Item,
		arg.Amount,
		arg.CategoryID,
		arg.UserID,
		arg.IsExcluded,
		arg.Note,
	)
	var i CreateJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Item,
		&i.Amount,
		&i.CategoryID,
		&i.UserID,
		&i.IsExcluded,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntriesByMonth = `-- name: ListJournalEntriesByMonth :many
SELECT
  je.id,
  je.transaction_date,
  je.item,
  je.amount,
  je.category_id,
  ec.category_name,
  ec.group_id,
  cg.group_name,
  je.is_excluded,
  je.note,
  je.created_at
FROM journal_entries je
JOIN expense_categories ec ON je.category_id = ec.id
JOIN category_groups cg ON ec.group_id = cg.id
WHERE je.user_id = $1
  AND je.transaction_date >= $2::date
  AND je.transaction_date < ($2::date + INTERVAL '1 month')
ORDER BY je.transaction_date DESC, je.id DESC
`

type ListJournalEntriesByMonthParams struct {
	UserID  int32       `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type ListJournalEntriesByMonthRow struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	CategoryID      int32       `json:"category_id"`
	CategoryName    string      `json:"category_name"`
	GroupID         int32       `json:"group_id"`
	GroupName       string      `json:"group_name"`
	IsExcluded      bool        `json:"is_excluded"`
	Note            *string     `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
}

// Joins category and group info for the response.
// Includes soft-deleted categories so historical entries display correctly.
func (q *Queries) ListJournalEntriesByMonth(ctx context.Context, arg ListJournalEntriesByMonthParams) ([]ListJournalEntriesByMonthRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalEntriesByMonthRow
	for rows.Next() {
		var i ListJournalEntriesByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Item,
			&i.Amount,
			&i.CategoryID,
			&i.CategoryName,
			&i.GroupID,
			&i.GroupName,
			&i.IsExcluded,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
