// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int32      `json:"id"`
	AccountCode *string    `json:"account_code"`
	AccountName *string    `json:"account_name"`
	AccountType *string    `json:"account_type"`
	UserID      int32      `json:"user_id"`
	Description *string    `json:"description"`
	IsDeleted   bool       `json:"is_deleted"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	Version     int32      `json:"version"`
}

type AccountTransaction struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Description     *string     `json:"description"`
	Amount          int32       `json:"amount"`
	AccountID       int32       `json:"account_id"`
	UserID          int32       `json:"user_id"`
	Note            *string     `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Version         int32       `json:"version"`
}

type Budget struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	MonthlyBudget int32     `json:"monthly_budget"`
	GoalText      *string   `json:"goal_text"`
	GoalAmount    int32     `json:"goal_amount"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CategoryGroup struct {
	ID              int32      `json:"id"`
	UserID          int32      `json:"user_id"`
	GroupName       string     `json:"group_name"`
	StatementTypeID int32      `json:"statement_type_id"`
	Description     *string    `json:"description"`
	IsDeleted       bool       `json:"is_deleted"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	Version         int32      `json:"version"`
}

type DailyNote struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	Date      pgtype.Date `json:"date"`
	Note      string      `json:"note"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ExpenseCategory struct {
	ID           int32      `json:"id"`
	CategoryCode *string    `json:"category_code"`
	CategoryName string     `json:"category_name"`
	UserID       int32      `json:"user_id"`
	GroupID      int32      `json:"group_id"`
	Description  *string    `json:"description"`
	IsDeleted    bool       `json:"is_deleted"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	Version      int32      `json:"version"`
}

type JournalEntry struct {
	ID              int32       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	Item            *string     `json:"item"`
	Amount          int32       `json:"amount"`
	IsExcluded      bool        `json:"is_excluded"`
	CategoryID      int32       `json:"category_id"`
	UserID          int32       `json:"user_id"`
	Note            *string     `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Version         int32       `json:"version"`
}

type MonthlyReview struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	YearMonth string    `json:"year_month"`
	Notes     []byte    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StatementType struct {
	ID                int32     `json:"id"`
	TypeCode          string    `json:"type_code"`
	StatementTypeName string    `json:"statement_type_name"`
	DisplayOrder      int32     `json:"display_order"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type User struct {
	ID           int32      `json:"id"`
	Email        string     `json:"email"`
	DisplayName  *string    `json:"display_name"`
	LastName     *string    `json:"last_name"`
	FirstName    *string    `json:"first_name"`
	PasswordHash string     `json:"password_hash"`
	Timezone     string     `json:"timezone"`
	AvatarUrl    *string    `json:"avatar_url"`
	LastLoginAt  *time.Time `json:"last_login_at"`
	IsDeleted    bool       `json:"is_deleted"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	Version      int32      `json:"version"`
}
