// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: monthly_reviews.sql

package db

import (
	"context"
)

const getMonthlyReview = `-- name: GetMonthlyReview :one
SELECT notes FROM monthly_reviews
WHERE user_id = $1 AND year_month = $2
`

type GetMonthlyReviewParams struct {
	UserID    int32  `json:"user_id"`
	YearMonth string `json:"year_month"`
}

func (q *Queries) GetMonthlyReview(ctx context.Context, arg GetMonthlyReviewParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMonthlyReview, arg.UserID, arg.YearMonth)
	var notes []byte
	err := row.Scan(&notes)
	return notes, err
}

const upsertMonthlyReview = `-- name: UpsertMonthlyReview :one
INSERT INTO monthly_reviews (user_id, year_month, notes)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, year_month) DO UPDATE
  SET notes      = EXCLUDED.notes,
      updated_at = NOW()
RETURNING notes
`

type UpsertMonthlyReviewParams struct {
	UserID    int32  `json:"user_id"`
	YearMonth string `json:"year_month"`
	Notes     []byte `json:"notes"`
}

func (q *Queries) UpsertMonthlyReview(ctx context.Context, arg UpsertMonthlyReviewParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyReview, arg.UserID, arg.YearMonth, arg.Notes)
	var notes []byte
	err := row.Scan(&notes)
	return notes, err
}
