// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recurring_expenses.sql

package db

import (
	"context"
)

const autoPostFixedRecurringForMonth = `-- name: AutoPostFixedRecurringForMonth :execrows
INSERT INTO journal_entries (
  transaction_date, item, amount, category_id, user_id, is_excluded, recurring_expense_id
)
SELECT
  make_date(
    EXTRACT(YEAR FROM m.month_start)::int,
    EXTRACT(MONTH FROM m.month_start)::int,
    LEAST(re.billing_day, EXTRACT(DAY FROM (m.month_start + INTERVAL '1 month - 1 day'))::int)
  ),
  re.name,
  re.amount,
  re.category_id,
  re.user_id,
  false,
  re.id
FROM recurring_expenses re
CROSS JOIN (SELECT ($2::text || '-01')::date AS month_start) AS m
WHERE re.user_id = $1
  AND re.type = 'fixed'
  AND re.amount IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM journal_entries je
    WHERE je.recurring_expense_id = re.id
      AND TO_CHAR(je.transaction_date, 'YYYY-MM') = $2::text
  )
`

type AutoPostFixedRecurringForMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

// Inserts journal entries for all of the user's FIXED recurring expenses that have a
// defined amount and are not yet linked to a journal entry in the given month. The
// transaction date is the billing day clamped to the last day of the month. The
// NOT EXISTS guard makes this idempotent per (recurring_expense, month); callers
// serialize concurrent first-requests of the month with an advisory lock to close the
// check-then-insert race window. Returns the number of entries inserted.
func (q *Queries) AutoPostFixedRecurringForMonth(ctx context.Context, arg AutoPostFixedRecurringForMonthParams) (int64, error) {
	result, err := q.db.Exec(ctx, autoPostFixedRecurringForMonth, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (user_id, name, emoji, billing_day, amount, type, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, emoji, billing_day, amount, type, category_id
`

type CreateRecurringExpenseParams struct {
	UserID     int32  `json:"user_id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	Type       string `json:"type"`
	CategoryID int32  `json:"category_id"`
}

type CreateRecurringExpenseRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	Type       string `json:"type"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (CreateRecurringExpenseRow, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.BillingDay,
		arg.Amount,
		arg.Type,
		arg.CategoryID,
	)
	var i CreateRecurringExpenseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.BillingDay,
		&i.Amount,
		&i.Type,
		&i.CategoryID,
	)
	return i, err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses WHERE id = $1 AND user_id = $2
`

type DeleteRecurringExpenseParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteRecurringExpense(ctx context.Context, arg DeleteRecurringExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpense, arg.ID, arg.UserID)
	return err
}

const existsRecurringJournalEntryForMonth = `-- name: ExistsRecurringJournalEntryForMonth :one
SELECT EXISTS (
  SELECT 1 FROM journal_entries je
  WHERE je.recurring_expense_id = $1
    AND je.user_id = $2
    AND TO_CHAR(je.transaction_date, 'YYYY-MM') = $3::text
) AS exists
`

type ExistsRecurringJournalEntryForMonthParams struct {
	RecurringExpenseID *int32 `json:"recurring_expense_id"`
	UserID             int32  `json:"user_id"`
	Column3            string `json:"column_3"`
}

// True when a journal entry already links this recurring expense in the given month.
func (q *Queries) ExistsRecurringJournalEntryForMonth(ctx context.Context, arg ExistsRecurringJournalEntryForMonthParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsRecurringJournalEntryForMonth, arg.RecurringExpenseID, arg.UserID, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRecurringExpenseByID = `-- name: GetRecurringExpenseByID :one
SELECT id, name, emoji, billing_day, amount, type, category_id
FROM recurring_expenses WHERE id = $1 AND user_id = $2
`

type GetRecurringExpenseByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetRecurringExpenseByIDRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	Type       string `json:"type"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) GetRecurringExpenseByID(ctx context.Context, arg GetRecurringExpenseByIDParams) (GetRecurringExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByID, arg.ID, arg.UserID)
	var i GetRecurringExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.BillingDay,
		&i.Amount,
		&i.Type,
		&i.CategoryID,
	)
	return i, err
}

const listPendingRecurring = `-- name: ListPendingRecurring :many
SELECT re.id, re.name, re.emoji, re.billing_day, re.amount, cg.group_name
FROM recurring_expenses re
JOIN expense_categories ec ON re.category_id = ec.id
JOIN category_groups cg ON ec.group_id = cg.id
WHERE re.user_id = $1
  AND re.type = 'variable'
  AND NOT EXISTS (
    SELECT 1 FROM journal_entries je
    WHERE je.recurring_expense_id = re.id
      AND TO_CHAR(je.transaction_date, 'YYYY-MM') = $2::text
  )
ORDER BY re.billing_day
`

type ListPendingRecurringParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

type ListPendingRecurringRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	GroupName  string `json:"group_name"`
}

func (q *Queries) ListPendingRecurring(ctx context.Context, arg ListPendingRecurringParams) ([]ListPendingRecurringRow, error) {
	rows, err := q.db.Query(ctx, listPendingRecurring, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRecurringRow
	for rows.Next() {
		var i ListPendingRecurringRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emoji,
			&i.BillingDay,
			&i.Amount,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpenses = `-- name: ListRecurringExpenses :many
SELECT re.id, re.name, re.emoji, re.billing_day, re.amount, re.type,
       re.category_id, ec.group_id, cg.group_name, ec.category_name
FROM recurring_expenses re
JOIN expense_categories ec ON re.category_id = ec.id
JOIN category_groups cg ON ec.group_id = cg.id
WHERE re.user_id = $1
ORDER BY re.billing_day, re.id
`

type ListRecurringExpensesRow struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Emoji        string `json:"emoji"`
	BillingDay   int16  `json:"billing_day"`
	Amount       *int32 `json:"amount"`
	Type         string `json:"type"`
	CategoryID   int32  `json:"category_id"`
	GroupID      int32  `json:"group_id"`
	GroupName    string `json:"group_name"`
	CategoryName string `json:"category_name"`
}

func (q *Queries) ListRecurringExpenses(ctx context.Context, userID int32) ([]ListRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, listRecurringExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurringExpensesRow
	for rows.Next() {
		var i ListRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emoji,
			&i.BillingDay,
			&i.Amount,
			&i.Type,
			&i.CategoryID,
			&i.GroupID,
			&i.GroupName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses
SET name = $3, emoji = $4, billing_day = $5, amount = $6, type = $7, category_id = $8, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, emoji, billing_day, amount, type, category_id
`

type UpdateRecurringExpenseParams struct {
	ID         int32  `json:"id"`
	UserID     int32  `json:"user_id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	Type       string `json:"type"`
	CategoryID int32  `json:"category_id"`
}

type UpdateRecurringExpenseRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Emoji      string `json:"emoji"`
	BillingDay int16  `json:"billing_day"`
	Amount     *int32 `json:"amount"`
	Type       string `json:"type"`
	CategoryID int32  `json:"category_id"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (UpdateRecurringExpenseRow, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.BillingDay,
		arg.Amount,
		arg.Type,
		arg.CategoryID,
	)
	var i UpdateRecurringExpenseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.BillingDay,
		&i.Amount,
		&i.Type,
		&i.CategoryID,
	)
	return i, err
}
