// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: savings_goals.sql

package db

import (
	"context"
)

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (user_id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, memo)
VALUES ($1, $2, $3, $4, $5, 0, $6, $7)
RETURNING id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
`

type CreateSavingsGoalParams struct {
	UserID        int32   `json:"user_id"`
	Name          string  `json:"name"`
	Emoji         string  `json:"emoji"`
	MonthlyAmount int32   `json:"monthly_amount"`
	TargetAmount  int32   `json:"target_amount"`
	Deadline      *string `json:"deadline"`
	Memo          string  `json:"memo"`
}

type CreateSavingsGoalRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (CreateSavingsGoalRow, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.MonthlyAmount,
		arg.TargetAmount,
		arg.Deadline,
		arg.Memo,
	)
	var i CreateSavingsGoalRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.MonthlyAmount,
		&i.TargetAmount,
		&i.AccumulatedAmount,
		&i.Deadline,
		&i.LastPostedMonth,
		&i.Memo,
	)
	return i, err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
DELETE FROM savings_goals WHERE id = $1 AND user_id = $2
`

type DeleteSavingsGoalParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.UserID)
	return err
}

const getSavingsGoalByID = `-- name: GetSavingsGoalByID :one
SELECT id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
FROM savings_goals WHERE id = $1 AND user_id = $2
`

type GetSavingsGoalByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSavingsGoalByIDRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) GetSavingsGoalByID(ctx context.Context, arg GetSavingsGoalByIDParams) (GetSavingsGoalByIDRow, error) {
	row := q.db.QueryRow(ctx, getSavingsGoalByID, arg.ID, arg.UserID)
	var i GetSavingsGoalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.MonthlyAmount,
		&i.TargetAmount,
		&i.AccumulatedAmount,
		&i.Deadline,
		&i.LastPostedMonth,
		&i.Memo,
	)
	return i, err
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
FROM savings_goals
WHERE user_id = $1
ORDER BY id
`

type ListSavingsGoalsRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) ListSavingsGoals(ctx context.Context, userID int32) ([]ListSavingsGoalsRow, error) {
	rows, err := q.db.Query(ctx, listSavingsGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavingsGoalsRow
	for rows.Next() {
		var i ListSavingsGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emoji,
			&i.MonthlyAmount,
			&i.TargetAmount,
			&i.AccumulatedAmount,
			&i.Deadline,
			&i.LastPostedMonth,
			&i.Memo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postMonthlySavings = `-- name: PostMonthlySavings :one
UPDATE savings_goals
SET accumulated_amount = accumulated_amount + $3,
    last_posted_month = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
`

type PostMonthlySavingsParams struct {
	ID                int32   `json:"id"`
	UserID            int32   `json:"user_id"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	LastPostedMonth   *string `json:"last_posted_month"`
}

type PostMonthlySavingsRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) PostMonthlySavings(ctx context.Context, arg PostMonthlySavingsParams) (PostMonthlySavingsRow, error) {
	row := q.db.QueryRow(ctx, postMonthlySavings,
		arg.ID,
		arg.UserID,
		arg.AccumulatedAmount,
		arg.LastPostedMonth,
	)
	var i PostMonthlySavingsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.MonthlyAmount,
		&i.TargetAmount,
		&i.AccumulatedAmount,
		&i.Deadline,
		&i.LastPostedMonth,
		&i.Memo,
	)
	return i, err
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals
SET name = $3, emoji = $4, monthly_amount = $5, target_amount = $6, deadline = $7, memo = $8, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
`

type UpdateSavingsGoalParams struct {
	ID            int32   `json:"id"`
	UserID        int32   `json:"user_id"`
	Name          string  `json:"name"`
	Emoji         string  `json:"emoji"`
	MonthlyAmount int32   `json:"monthly_amount"`
	TargetAmount  int32   `json:"target_amount"`
	Deadline      *string `json:"deadline"`
	Memo          string  `json:"memo"`
}

type UpdateSavingsGoalRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (UpdateSavingsGoalRow, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.MonthlyAmount,
		arg.TargetAmount,
		arg.Deadline,
		arg.Memo,
	)
	var i UpdateSavingsGoalRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.MonthlyAmount,
		&i.TargetAmount,
		&i.AccumulatedAmount,
		&i.Deadline,
		&i.LastPostedMonth,
		&i.Memo,
	)
	return i, err
}
