// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: statement_types.sql

package db

import (
	"context"
)

const listStatementTypes = `-- name: ListStatementTypes :many
SELECT id, type_code, statement_type_name, display_order
FROM statement_types
ORDER BY display_order ASC
`

type ListStatementTypesRow struct {
	ID                int32  `json:"id"`
	TypeCode          string `json:"type_code"`
	StatementTypeName string `json:"statement_type_name"`
	DisplayOrder      int32  `json:"display_order"`
}

func (q *Queries) ListStatementTypes(ctx context.Context) ([]ListStatementTypesRow, error) {
	rows, err := q.db.Query(ctx, listStatementTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementTypesRow
	for rows.Next() {
		var i ListStatementTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeCode,
			&i.StatementTypeName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
