// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: surplus_allocations.sql

package db

import (
	"context"
	"time"
)

const incrementSavingsGoalAccumulated = `-- name: IncrementSavingsGoalAccumulated :one
UPDATE savings_goals
SET accumulated_amount = accumulated_amount + $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, emoji, monthly_amount, target_amount, accumulated_amount, deadline, last_posted_month, memo
`

type IncrementSavingsGoalAccumulatedParams struct {
	ID                int32 `json:"id"`
	UserID            int32 `json:"user_id"`
	AccumulatedAmount int32 `json:"accumulated_amount"`
}

type IncrementSavingsGoalAccumulatedRow struct {
	ID                int32   `json:"id"`
	Name              string  `json:"name"`
	Emoji             string  `json:"emoji"`
	MonthlyAmount     int32   `json:"monthly_amount"`
	TargetAmount      int32   `json:"target_amount"`
	AccumulatedAmount int32   `json:"accumulated_amount"`
	Deadline          *string `json:"deadline"`
	LastPostedMonth   *string `json:"last_posted_month"`
	Memo              string  `json:"memo"`
}

func (q *Queries) IncrementSavingsGoalAccumulated(ctx context.Context, arg IncrementSavingsGoalAccumulatedParams) (IncrementSavingsGoalAccumulatedRow, error) {
	row := q.db.QueryRow(ctx, incrementSavingsGoalAccumulated, arg.ID, arg.UserID, arg.AccumulatedAmount)
	var i IncrementSavingsGoalAccumulatedRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.MonthlyAmount,
		&i.TargetAmount,
		&i.AccumulatedAmount,
		&i.Deadline,
		&i.LastPostedMonth,
		&i.Memo,
	)
	return i, err
}

const insertSurplusAllocation = `-- name: InsertSurplusAllocation :one
INSERT INTO surplus_allocations (user_id, year_month, amount, destination, savings_goal_id)
VALUES ($1, $2::text, $3, $4, $5)
RETURNING id, year_month, amount, destination, savings_goal_id, created_at
`

type InsertSurplusAllocationParams struct {
	UserID        int32  `json:"user_id"`
	Column2       string `json:"column_2"`
	Amount        int32  `json:"amount"`
	Destination   string `json:"destination"`
	SavingsGoalID *int32 `json:"savings_goal_id"`
}

type InsertSurplusAllocationRow struct {
	ID            int32     `json:"id"`
	YearMonth     string    `json:"year_month"`
	Amount        int32     `json:"amount"`
	Destination   string    `json:"destination"`
	SavingsGoalID *int32    `json:"savings_goal_id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertSurplusAllocation(ctx context.Context, arg InsertSurplusAllocationParams) (InsertSurplusAllocationRow, error) {
	row := q.db.QueryRow(ctx, insertSurplusAllocation,
		arg.UserID,
		arg.Column2,
		arg.Amount,
		arg.Destination,
		arg.SavingsGoalID,
	)
	var i InsertSurplusAllocationRow
	err := row.Scan(
		&i.ID,
		&i.YearMonth,
		&i.Amount,
		&i.Destination,
		&i.SavingsGoalID,
		&i.CreatedAt,
	)
	return i, err
}

const listSurplusAllocationsByMonth = `-- name: ListSurplusAllocationsByMonth :many
SELECT id, year_month, amount, destination, savings_goal_id, created_at
FROM surplus_allocations
WHERE user_id = $1 AND year_month = $2::text
ORDER BY id
`

type ListSurplusAllocationsByMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

type ListSurplusAllocationsByMonthRow struct {
	ID            int32     `json:"id"`
	YearMonth     string    `json:"year_month"`
	Amount        int32     `json:"amount"`
	Destination   string    `json:"destination"`
	SavingsGoalID *int32    `json:"savings_goal_id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) ListSurplusAllocationsByMonth(ctx context.Context, arg ListSurplusAllocationsByMonthParams) ([]ListSurplusAllocationsByMonthRow, error) {
	rows, err := q.db.Query(ctx, listSurplusAllocationsByMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSurplusAllocationsByMonthRow
	for rows.Next() {
		var i ListSurplusAllocationsByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.YearMonth,
			&i.Amount,
			&i.Destination,
			&i.SavingsGoalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAllocatedByMonth = `-- name: SumAllocatedByMonth :one
SELECT COALESCE(SUM(amount), 0)::INTEGER AS total
FROM surplus_allocations
WHERE user_id = $1 AND year_month = $2::text
`

type SumAllocatedByMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

// Returns the total allocated surplus (budget + savings) for the user and month.
func (q *Queries) SumAllocatedByMonth(ctx context.Context, arg SumAllocatedByMonthParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumAllocatedByMonth, arg.UserID, arg.Column2)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const sumSavingsAllocatedByMonth = `-- name: SumSavingsAllocatedByMonth :one
SELECT COALESCE(SUM(amount), 0)::INTEGER AS total
FROM surplus_allocations
WHERE user_id = $1 AND year_month = $2::text AND destination = 'savings'
`

type SumSavingsAllocatedByMonthParams struct {
	UserID  int32  `json:"user_id"`
	Column2 string `json:"column_2"`
}

// Returns the total savings-destined allocations for the user and month.
// Used to subtract from variable_budget in the budget summary.
func (q *Queries) SumSavingsAllocatedByMonth(ctx context.Context, arg SumSavingsAllocatedByMonthParams) (int32, error) {
	row := q.db.QueryRow(ctx, sumSavingsAllocatedByMonth, arg.UserID, arg.Column2)
	var total int32
	err := row.Scan(&total)
	return total, err
}
